<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Role"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="12.756">
  <properties />
            <testcase name="delRoleSuccess" time="12.756" classname="com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test">
                <failure type="java.lang.AssertionError"
                  message="期望的文字是 [操1作成功] 但是找到了 [操作成功]"
              >
<![CDATA[java.lang.AssertionError: 期望的文字是 [操1作成功] 但是找到了 [操作成功]
  org.testng.Assert.fail(Assert.java:96)
  com.wymall.test.utils.SeleniumUtil.isTextCorrect(SeleniumUtil.java:336)
  com.wymall.test.utils.actions.impl.CheckTipsText.doAction(CheckTipsText.java:23)
  com.wymall.test.utils.SuperAction.parseExcel(SuperAction.java:277)
  com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test.delRoleSuccess(RolePage_004_delRoleSuccess_Test.java:8)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
  org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
