<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ake-PC" name="com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test" tests="1" failures="0" timestamp="28 Aug 2018 02:52:52 GMT" time="12.211" errors="1">
  <testcase name="delRoleSuccess" time="12.211" classname="com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test">
    <error type="java.lang.AssertionError" message="期望的文字是 [操1作成功] 但是找到了 [操作成功]">
      <![CDATA[java.lang.AssertionError: 期望的文字是 [操1作成功] 但是找到了 [操作成功]
	at org.testng.Assert.fail(Assert.java:94)
	at com.wymall.test.utils.SeleniumUtil.isTextCorrect(SeleniumUtil.java:336)
	at com.wymall.test.utils.actions.impl.CheckTipsText.doAction(CheckTipsText.java:23)
	at com.wymall.test.utils.SuperAction.parseExcel(SuperAction.java:277)
	at com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test.delRoleSuccess(RolePage_004_delRoleSuccess_Test.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- delRoleSuccess -->
</testsuite> <!-- com.wymall.test.testcases.system.role.RolePage_004_delRoleSuccess_Test -->
